# Generated by Django 4.2.23 on 2025-08-03 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CCTV', '0002_camera'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=200)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_labels', to='CCTV.camera')),
            ],
        ),
    ]
