# Generated by Django 4.2.23 on 2025-08-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCTV', '0003_targetlabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='rtsp_url',
            field=models.CharField(max_length=500),
        ),
    ]
