# Generated by Django 4.2.23 on 2025-08-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCTV', '0004_alter_camera_rtsp_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetlabel',
            name='display_name',
            field=models.CharField(blank=True, help_text='화면에 표시할 이름', max_length=100),
        ),
    ]
