# Generated by Django 4.2.23 on 2025-08-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCTV', '0005_targetlabel_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetlabel',
            name='display_name',
            field=models.CharField(help_text='화면에 표시할 이름', max_length=100),
        ),
        migrations.AlterField(
            model_name='targetlabel',
            name='label_name',
            field=models.CharField(help_text='객체 탐지 자연어 토큰', max_length=200),
        ),
    ]
