# Generated by Django 4.2.23 on 2025-08-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCTV', '0006_alter_targetlabel_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetlabel',
            name='has_alert',
            field=models.BooleanField(default=False, verbose_name='경고 여부'),
        ),
    ]
