# Generated by Django 4.2.23 on 2025-08-05 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CCTV', '0009_detectionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='건물명 (예: 대학본부, 공학관)', max_length=100)),
                ('address', models.CharField(blank=True, help_text='주소', max_length=200)),
                ('description', models.TextField(blank=True, help_text='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '위치',
                'verbose_name_plural': '위치들',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='층 이름 (예: 1층, 2층, 지하1층)', max_length=100)),
                ('floor_number', models.IntegerField(help_text='정렬용 층수 (-1, 1, 2, 3...)')),
                ('map_image', models.ImageField(help_text='지도 이미지 파일', upload_to='maps/%Y/%m/')),
                ('top_left_lat', models.FloatField(blank=True, help_text='좌상단 위도', null=True)),
                ('top_left_lon', models.FloatField(blank=True, help_text='좌상단 경도', null=True)),
                ('bottom_right_lat', models.FloatField(blank=True, help_text='우하단 위도', null=True)),
                ('bottom_right_lon', models.FloatField(blank=True, help_text='우하단 경도', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='map.location', verbose_name='위치')),
            ],
            options={
                'verbose_name': '층',
                'verbose_name_plural': '층들',
                'ordering': ['location', 'floor_number'],
                'unique_together': {('location', 'floor_number')},
            },
        ),
        migrations.CreateModel(
            name='CameraPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_position', models.FloatField(help_text='지도상 X 좌표 (퍼센트, 0-100)')),
                ('y_position', models.FloatField(help_text='지도상 Y 좌표 (퍼센트, 0-100)')),
                ('is_active', models.BooleanField(default=True, help_text='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='CCTV.camera', verbose_name='카메라')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_positions', to='map.floor', verbose_name='층')),
            ],
            options={
                'verbose_name': '카메라 위치',
                'verbose_name_plural': '카메라 위치들',
                'unique_together': {('camera', 'floor')},
            },
        ),
    ]
