# Generated by Django 4.2.23 on 2025-08-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='base_floor_altitude',
            field=models.FloatField(blank=True, help_text='1층 기준 GPS 고도 (미터, 예: 100.0)', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='floor_height_interval',
            field=models.FloatField(blank=True, help_text='층간 높이 간격 (미터, 예: 1.5)', null=True),
        ),
    ]
