# Generated by Django 4.2.23 on 2025-08-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_location_base_floor_altitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='base_floor_altitude',
            field=models.FloatField(default=1, help_text='1층 기준 GPS 고도 (미터, 예: 100.0)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='floor_height_interval',
            field=models.FloatField(default=1, help_text='층간 높이 간격 (미터, 예: 1.5)'),
            preserve_default=False,
        ),
    ]
