# Generated by Django 4.2.23 on 2025-06-22 12:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_key_value', models.CharField(help_text='RFID 카드의 UID (Hex 형태)', max_length=20, unique=True, verbose_name='카드 고유키')),
                ('card_alias', models.CharField(help_text='예: 홍길동 카드, 임시카드1', max_length=100, verbose_name='카드 별칭')),
                ('card_level', models.IntegerField(default=5, help_text='0=최고 권한, 5=최저 권한', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='카드 보안 등급')),
                ('regist_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('who_add', models.CharField(help_text='카드를 등록한 관리자 이름', max_length=100, verbose_name='등록자')),
                ('last_modify_date', models.DateTimeField(auto_now=True, verbose_name='마지막 수정일시')),
                ('last_modify_who', models.CharField(blank=True, max_length=100, verbose_name='마지막 수정자')),
                ('is_active', models.BooleanField(default=True, help_text='False시 카드 사용 불가', verbose_name='카드 활성 상태')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='유효 시작일')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='유효 종료일')),
            ],
            options={
                'verbose_name': 'RFID 카드',
                'verbose_name_plural': 'RFID 카드 목록',
                'db_table': 'card',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='예: 회의실A, 서버실, 사무실', max_length=100, verbose_name='방 이름')),
                ('location', models.CharField(help_text='예: 3층 동쪽, GPS좌표, 상세 주소', max_length=150, verbose_name='방 위치')),
                ('required_level', models.IntegerField(help_text='0=최고 권한, 5=최저 권한', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='필요 보안 등급')),
                ('device_id', models.CharField(help_text='각 아두이노 기기의 고유 식별자', max_length=20, unique=True, verbose_name='아두이노 기기 ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='False시 모든 출입 차단', verbose_name='방 사용 가능 여부')),
                ('door_status', models.BooleanField(default=False, help_text='True=열림, False=닫힘', verbose_name='현재 문 상태')),
                ('last_door_change', models.DateTimeField(blank=True, null=True, verbose_name='마지막 문 상태 변경 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
            ],
            options={
                'verbose_name': '방 정보',
                'verbose_name_plural': '방 정보 목록',
                'db_table': 'room_info',
                'indexes': [models.Index(fields=['device_id'], name='room_info_device__d45de3_idx'), models.Index(fields=['required_level'], name='room_info_require_3dcd23_idx')],
            },
        ),
        migrations.CreateModel(
            name='CardUseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_key_backup', models.CharField(help_text='카드 삭제 시 추적을 위한 백업', max_length=20, verbose_name='카드키 백업')),
                ('room_name_backup', models.CharField(help_text='방 삭제 시 추적을 위한 백업', max_length=100, verbose_name='방 이름 백업')),
                ('access_result', models.CharField(choices=[('granted', '출입 허용'), ('denied', '출입 거부'), ('error', '시스템 오류')], default='denied', max_length=10, verbose_name='출입 결과')),
                ('denial_reason', models.CharField(blank=True, help_text='출입 거부 시 상세 사유', max_length=100, verbose_name='거부 사유')),
                ('use_date', models.DateTimeField(auto_now_add=True, verbose_name='사용일시')),
                ('server_response_time', models.FloatField(blank=True, help_text='성능 모니터링용', null=True, verbose_name='서버 응답 시간(ms)')),
                ('card', models.ForeignKey(help_text='카드 삭제 시에도 로그는 유지', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='use_logs', to='RFID.card', verbose_name='사용된 카드')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='RFID.room', verbose_name='출입 시도 방')),
            ],
            options={
                'verbose_name': '카드 사용 로그',
                'verbose_name_plural': '카드 사용 로그 목록',
                'db_table': 'card_use_log',
                'ordering': ['-use_date'],
            },
        ),
        migrations.CreateModel(
            name='CardModifyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_alias_before', models.CharField(blank=True, max_length=100, verbose_name='변경 전 카드 별칭')),
                ('card_alias_after', models.CharField(blank=True, max_length=100, verbose_name='변경 후 카드 별칭')),
                ('card_level_before', models.IntegerField(verbose_name='변경 전 보안 등급')),
                ('card_level_after', models.IntegerField(verbose_name='변경 후 보안 등급')),
                ('is_active_before', models.BooleanField(verbose_name='변경 전 활성 상태')),
                ('is_active_after', models.BooleanField(verbose_name='변경 후 활성 상태')),
                ('modify_date', models.DateTimeField(auto_now_add=True, verbose_name='수정일시')),
                ('modify_who', models.CharField(max_length=100, verbose_name='수정자')),
                ('modify_reason', models.TextField(blank=True, verbose_name='수정 사유')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modify_logs', to='RFID.card', verbose_name='수정된 카드')),
            ],
            options={
                'verbose_name': '카드 수정 로그',
                'verbose_name_plural': '카드 수정 로그 목록',
                'db_table': 'card_modify_log',
                'ordering': ['-modify_date'],
            },
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['card_key_value'], name='card_card_ke_4f7193_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['card_level'], name='card_card_le_864140_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['is_active'], name='card_is_acti_c8682b_idx'),
        ),
        migrations.AddIndex(
            model_name='carduselog',
            index=models.Index(fields=['card', 'use_date'], name='card_use_lo_card_id_7fb40c_idx'),
        ),
        migrations.AddIndex(
            model_name='carduselog',
            index=models.Index(fields=['room', 'use_date'], name='card_use_lo_room_id_e98f26_idx'),
        ),
        migrations.AddIndex(
            model_name='carduselog',
            index=models.Index(fields=['use_date'], name='card_use_lo_use_dat_a19562_idx'),
        ),
        migrations.AddIndex(
            model_name='carduselog',
            index=models.Index(fields=['access_result'], name='card_use_lo_access__03e496_idx'),
        ),
        migrations.AddIndex(
            model_name='carduselog',
            index=models.Index(fields=['card_key_backup'], name='card_use_lo_card_ke_8d4ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='cardmodifylog',
            index=models.Index(fields=['card', 'modify_date'], name='card_modify_card_id_7308ad_idx'),
        ),
        migrations.AddIndex(
            model_name='cardmodifylog',
            index=models.Index(fields=['modify_date'], name='card_modify_modify__b6a859_idx'),
        ),
    ]
