# Generated by Django 4.2.23 on 2025-06-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFID', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'RFID 카드', 'verbose_name_plural': 'Card : RFID 카드 목록'},
        ),
        migrations.AlterModelOptions(
            name='cardmodifylog',
            options={'ordering': ['-modify_date'], 'verbose_name': '카드 수정 로그', 'verbose_name_plural': 'CardModifyLog : 카드 수정 로그 목록'},
        ),
        migrations.AlterModelOptions(
            name='carduselog',
            options={'ordering': ['-use_date'], 'verbose_name': '카드 사용 로그', 'verbose_name_plural': 'CardUseLog : 카드 사용 로그 목록'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': '방 정보', 'verbose_name_plural': 'ROOM : 방 정보 목록'},
        ),
        migrations.AlterField(
            model_name='card',
            name='card_key_value',
            field=models.CharField(help_text='RFID 카드의 UID (Hex 형태)', max_length=20, verbose_name='카드 고유키'),
        ),
    ]
