# Generated by Django 4.2.23 on 2025-06-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFID', '0002_alter_card_options_alter_cardmodifylog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='아두이노 내부 Preferences->ap_name', max_length=10, verbose_name='모듈 고유 코드')),
            ],
        ),
    ]
