# Generated by Django 4.2.23 on 2025-06-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RFID', '0003_moduleinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moduleinfo',
            options={'verbose_name': '아두이노 정보 저장', 'verbose_name_plural': 'ModuleInfo : 아두이노 디바이스 정보'},
        ),
        migrations.AlterModelTable(
            name='moduleinfo',
            table='module_info',
        ),
    ]
