# Generated by Django 4.2.23 on 2025-07-24 01:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CameraConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="카메라 식별명", max_length=100, unique=True
                    ),
                ),
                (
                    "api_key",
                    models.CharField(help_text="ROBOFLOW API 키", max_length=255),
                ),
                (
                    "workspace_name",
                    models.CharField(
                        help_text="ROBOFLOW 워크스페이스명", max_length=100
                    ),
                ),
                (
                    "workflow_id",
                    models.CharField(help_text="워크플로우 ID", max_length=100),
                ),
                (
                    "rtsp_url",
                    models.CharField(help_text="RTSP 스트림 URL", max_length=500),
                ),
                (
                    "max_fps",
                    models.IntegerField(
                        default=15,
                        help_text="최대 FPS (1-60)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="카메라 활성화 상태"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "카메라 설정",
                "verbose_name_plural": "카메라 설정",
                "ordering": ["name"],
            },
        ),
    ]
