# Generated by Django 4.2.23 on 2025-08-05 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CCTV", "0007_targetlabel_has_alert"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CameraConfig",
        ),
    ]
