# Generated by Django 4.2.23 on 2025-08-05 02:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("CCTV", "0008_delete_cameraconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "camera_name",
                    models.CharField(help_text="카메라 이름 (로그용)", max_length=100),
                ),
                (
                    "camera_location",
                    models.CharField(help_text="카메라 위치 (로그용)", max_length=200),
                ),
                (
                    "detected_object",
                    models.CharField(help_text="탐지된 객체", max_length=100),
                ),
                (
                    "object_count",
                    models.PositiveIntegerField(help_text="탐지된 객체 개수"),
                ),
                ("confidence", models.FloatField(help_text="탐지 신뢰도 (0.0-1.0)")),
                (
                    "has_alert",
                    models.BooleanField(default=False, help_text="경고 객체 여부"),
                ),
                (
                    "screenshot_path",
                    models.CharField(
                        blank=True,
                        help_text="스크린샷 파일 경로",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="탐지 시각"
                    ),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detection_logs",
                        to="CCTV.camera",
                    ),
                ),
            ],
            options={
                "verbose_name": "탐지 로그",
                "verbose_name_plural": "탐지 로그들",
                "ordering": ["-detected_at"],
            },
        ),
    ]
